#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER FieldId
The ID of the field to add.
.OUTPUTS

AddFieldBean<PSCustomObject>
#>

function Initialize-AddFieldBean {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${FieldId}
    )

    Process {
        'Creating PSCustomObject: PSJira => AddFieldBean' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $FieldId) {
            throw "invalid value for 'FieldId', 'FieldId' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "fieldId" = ${FieldId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AddFieldBean<PSCustomObject>

.DESCRIPTION

Convert from JSON to AddFieldBean<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AddFieldBean<PSCustomObject>
#>
function ConvertFrom-JsonToAddFieldBean {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSJira => AddFieldBean' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in AddFieldBean
        $AllProperties = ("fieldId")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'fieldId' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "fieldId"))) {
            throw "Error! JSON cannot be serialized due to the required property 'fieldId' missing."
        } else {
            $FieldId = $JsonParameters.PSobject.Properties["fieldId"].value
        }

        $PSO = [PSCustomObject]@{
            "fieldId" = ${FieldId}
        }

        return $PSO
    }

}

