#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER ElementErrors
No description available.
.PARAMETER FailedElementNumber
No description available.
.PARAMETER Status
No description available.
.OUTPUTS

BulkOperationErrorResult<PSCustomObject>
#>

function Initialize-BulkOperationErrorResult {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ElementErrors},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${FailedElementNumber},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Status}
    )

    Process {
        'Creating PSCustomObject: PSJira => BulkOperationErrorResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "elementErrors" = ${ElementErrors}
            "failedElementNumber" = ${FailedElementNumber}
            "status" = ${Status}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to BulkOperationErrorResult<PSCustomObject>

.DESCRIPTION

Convert from JSON to BulkOperationErrorResult<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

BulkOperationErrorResult<PSCustomObject>
#>
function ConvertFrom-JsonToBulkOperationErrorResult {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSJira => BulkOperationErrorResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in BulkOperationErrorResult
        $AllProperties = ("elementErrors", "failedElementNumber", "status")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "elementErrors"))) { #optional property not found
            $ElementErrors = $null
        } else {
            $ElementErrors = $JsonParameters.PSobject.Properties["elementErrors"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "failedElementNumber"))) { #optional property not found
            $FailedElementNumber = $null
        } else {
            $FailedElementNumber = $JsonParameters.PSobject.Properties["failedElementNumber"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "status"))) { #optional property not found
            $Status = $null
        } else {
            $Status = $JsonParameters.PSobject.Properties["status"].value
        }

        $PSO = [PSCustomObject]@{
            "elementErrors" = ${ElementErrors}
            "failedElementNumber" = ${FailedElementNumber}
            "status" = ${Status}
        }

        return $PSO
    }

}

