#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

The response code and messages related to any requested transition.

.PARAMETER ErrorCollection
No description available.
.PARAMETER Status
No description available.
.PARAMETER WarningCollection
No description available.
.OUTPUTS

CreatedIssueTransition<PSCustomObject>
#>

function Initialize-CreatedIssueTransition {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ErrorCollection},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Status},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${WarningCollection}
    )

    Process {
        'Creating PSCustomObject: PSJira => CreatedIssueTransition' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "errorCollection" = ${ErrorCollection}
            "status" = ${Status}
            "warningCollection" = ${WarningCollection}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CreatedIssueTransition<PSCustomObject>

.DESCRIPTION

Convert from JSON to CreatedIssueTransition<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CreatedIssueTransition<PSCustomObject>
#>
function ConvertFrom-JsonToCreatedIssueTransition {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSJira => CreatedIssueTransition' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CreatedIssueTransition
        $AllProperties = ("errorCollection", "status", "warningCollection")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "errorCollection"))) { #optional property not found
            $ErrorCollection = $null
        } else {
            $ErrorCollection = $JsonParameters.PSobject.Properties["errorCollection"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "status"))) { #optional property not found
            $Status = $null
        } else {
            $Status = $JsonParameters.PSobject.Properties["status"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "warningCollection"))) { #optional property not found
            $WarningCollection = $null
        } else {
            $WarningCollection = $JsonParameters.PSobject.Properties["warningCollection"].value
        }

        $PSO = [PSCustomObject]@{
            "errorCollection" = ${ErrorCollection}
            "status" = ${Status}
            "warningCollection" = ${WarningCollection}
        }

        return $PSO
    }

}

