#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Default values to update.

.PARAMETER DefaultValues
No description available.
.OUTPUTS

CustomFieldContextDefaultValueUpdate<PSCustomObject>
#>

function Initialize-CustomFieldContextDefaultValueUpdate {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${DefaultValues}
    )

    Process {
        'Creating PSCustomObject: PSJira => CustomFieldContextDefaultValueUpdate' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "defaultValues" = ${DefaultValues}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CustomFieldContextDefaultValueUpdate<PSCustomObject>

.DESCRIPTION

Convert from JSON to CustomFieldContextDefaultValueUpdate<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CustomFieldContextDefaultValueUpdate<PSCustomObject>
#>
function ConvertFrom-JsonToCustomFieldContextDefaultValueUpdate {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSJira => CustomFieldContextDefaultValueUpdate' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CustomFieldContextDefaultValueUpdate
        $AllProperties = ("defaultValues")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "defaultValues"))) { #optional property not found
            $DefaultValues = $null
        } else {
            $DefaultValues = $JsonParameters.PSobject.Properties["defaultValues"].value
        }

        $PSO = [PSCustomObject]@{
            "defaultValues" = ${DefaultValues}
        }

        return $PSO
    }

}

