#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

The data classification.

.PARAMETER Classifications
The data classifications.
.OUTPUTS

DataClassificationLevelsBean<PSCustomObject>
#>

function Initialize-DataClassificationLevelsBean {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Classifications}
    )

    Process {
        'Creating PSCustomObject: PSJira => DataClassificationLevelsBean' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "classifications" = ${Classifications}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to DataClassificationLevelsBean<PSCustomObject>

.DESCRIPTION

Convert from JSON to DataClassificationLevelsBean<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

DataClassificationLevelsBean<PSCustomObject>
#>
function ConvertFrom-JsonToDataClassificationLevelsBean {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSJira => DataClassificationLevelsBean' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in DataClassificationLevelsBean
        $AllProperties = ("classifications")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "classifications"))) { #optional property not found
            $Classifications = $null
        } else {
            $Classifications = $JsonParameters.PSobject.Properties["classifications"].value
        }

        $PSO = [PSCustomObject]@{
            "classifications" = ${Classifications}
        }

        return $PSO
    }

}

