#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

A clause that asserts whether a field was changed. For example, `status CHANGED AFTER startOfMonth(-1M)`.See [CHANGED](https://confluence.atlassian.com/x/dgiiLQ#Advancedsearching-operatorsreference-CHANGEDCHANGED) for more information about the CHANGED operator.

.PARAMETER Field
No description available.
.PARAMETER Operator
The operator applied to the field.
.PARAMETER Predicates
The list of time predicates.
.OUTPUTS

FieldChangedClause<PSCustomObject>
#>

function Initialize-FieldChangedClause {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Field},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("changed")]
        [String]
        ${Operator},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Predicates}
    )

    Process {
        'Creating PSCustomObject: PSJira => FieldChangedClause' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Field) {
            throw "invalid value for 'Field', 'Field' cannot be null."
        }

        if ($null -eq $Operator) {
            throw "invalid value for 'Operator', 'Operator' cannot be null."
        }

        if ($null -eq $Predicates) {
            throw "invalid value for 'Predicates', 'Predicates' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "field" = ${Field}
            "operator" = ${Operator}
            "predicates" = ${Predicates}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to FieldChangedClause<PSCustomObject>

.DESCRIPTION

Convert from JSON to FieldChangedClause<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

FieldChangedClause<PSCustomObject>
#>
function ConvertFrom-JsonToFieldChangedClause {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSJira => FieldChangedClause' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in FieldChangedClause
        $AllProperties = ("field", "operator", "predicates")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'field' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "field"))) {
            throw "Error! JSON cannot be serialized due to the required property 'field' missing."
        } else {
            $Field = $JsonParameters.PSobject.Properties["field"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "operator"))) {
            throw "Error! JSON cannot be serialized due to the required property 'operator' missing."
        } else {
            $Operator = $JsonParameters.PSobject.Properties["operator"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "predicates"))) {
            throw "Error! JSON cannot be serialized due to the required property 'predicates' missing."
        } else {
            $Predicates = $JsonParameters.PSobject.Properties["predicates"].value
        }

        $PSO = [PSCustomObject]@{
            "field" = ${Field}
            "operator" = ${Operator}
            "predicates" = ${Predicates}
        }

        return $PSO
    }

}

