#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

List of Issue Ids Or Keys that are to be archived or unarchived

.PARAMETER IssueIdsOrKeys
No description available.
.OUTPUTS

IssueArchivalSyncRequest<PSCustomObject>
#>

function Initialize-IssueArchivalSyncRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${IssueIdsOrKeys}
    )

    Process {
        'Creating PSCustomObject: PSJira => IssueArchivalSyncRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "issueIdsOrKeys" = ${IssueIdsOrKeys}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to IssueArchivalSyncRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to IssueArchivalSyncRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

IssueArchivalSyncRequest<PSCustomObject>
#>
function ConvertFrom-JsonToIssueArchivalSyncRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSJira => IssueArchivalSyncRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in IssueArchivalSyncRequest
        $AllProperties = ("issueIdsOrKeys")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "issueIdsOrKeys"))) { #optional property not found
            $IssueIdsOrKeys = $null
        } else {
            $IssueIdsOrKeys = $JsonParameters.PSobject.Properties["issueIdsOrKeys"].value
        }

        $PSO = [PSCustomObject]@{
            "issueIdsOrKeys" = ${IssueIdsOrKeys}
        }

        return $PSO
    }

}

