#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

A list of the issues matched to a JQL query or details of errors encountered during matching.

.PARAMETER Errors
A list of errors.
.PARAMETER MatchedIssues
A list of issue IDs.
.OUTPUTS

IssueMatchesForJQL<PSCustomObject>
#>

function Initialize-IssueMatchesForJQL {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Errors},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Int64[]]
        ${MatchedIssues}
    )

    Process {
        'Creating PSCustomObject: PSJira => IssueMatchesForJQL' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Errors) {
            throw "invalid value for 'Errors', 'Errors' cannot be null."
        }

        if ($null -eq $MatchedIssues) {
            throw "invalid value for 'MatchedIssues', 'MatchedIssues' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "errors" = ${Errors}
            "matchedIssues" = ${MatchedIssues}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to IssueMatchesForJQL<PSCustomObject>

.DESCRIPTION

Convert from JSON to IssueMatchesForJQL<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

IssueMatchesForJQL<PSCustomObject>
#>
function ConvertFrom-JsonToIssueMatchesForJQL {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSJira => IssueMatchesForJQL' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in IssueMatchesForJQL
        $AllProperties = ("errors", "matchedIssues")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'errors' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "errors"))) {
            throw "Error! JSON cannot be serialized due to the required property 'errors' missing."
        } else {
            $Errors = $JsonParameters.PSobject.Properties["errors"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "matchedIssues"))) {
            throw "Error! JSON cannot be serialized due to the required property 'matchedIssues' missing."
        } else {
            $MatchedIssues = $JsonParameters.PSobject.Properties["matchedIssues"].value
        }

        $PSO = [PSCustomObject]@{
            "errors" = ${Errors}
            "matchedIssues" = ${MatchedIssues}
        }

        return $PSO
    }

}

