#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Details of an issue priority.

.PARAMETER Description
The description of the priority.
.PARAMETER IconUrl
The URL of an icon for the priority. Accepted protocols are HTTP and HTTPS. Built in icons can also be used.
.PARAMETER Name
The name of the priority. Must be unique.
.PARAMETER StatusColor
The status color of the priority in 3-digit or 6-digit hexadecimal format.
.OUTPUTS

UpdatePriorityDetails<PSCustomObject>
#>

function Initialize-UpdatePriorityDetails {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("/images/icons/priorities/blocker.png", "/images/icons/priorities/critical.png", "/images/icons/priorities/high.png", "/images/icons/priorities/highest.png", "/images/icons/priorities/low.png", "/images/icons/priorities/lowest.png", "/images/icons/priorities/major.png", "/images/icons/priorities/medium.png", "/images/icons/priorities/minor.png", "/images/icons/priorities/trivial.png")]
        [String]
        ${IconUrl},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${StatusColor}
    )

    Process {
        'Creating PSCustomObject: PSJira => UpdatePriorityDetails' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Description -and $Description.length -gt 255) {
            throw "invalid value for 'Description', the character length must be smaller than or equal to 255."
        }

        if (!$IconUrl -and $IconUrl.length -gt 255) {
            throw "invalid value for 'IconUrl', the character length must be smaller than or equal to 255."
        }

        if (!$Name -and $Name.length -gt 60) {
            throw "invalid value for 'Name', the character length must be smaller than or equal to 60."
        }


        $PSO = [PSCustomObject]@{
            "description" = ${Description}
            "iconUrl" = ${IconUrl}
            "name" = ${Name}
            "statusColor" = ${StatusColor}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to UpdatePriorityDetails<PSCustomObject>

.DESCRIPTION

Convert from JSON to UpdatePriorityDetails<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

UpdatePriorityDetails<PSCustomObject>
#>
function ConvertFrom-JsonToUpdatePriorityDetails {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSJira => UpdatePriorityDetails' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json
        $UpdatePriorityDetailsAdditionalProperties = @{}

        # check if Json contains properties not defined in UpdatePriorityDetails
        $AllProperties = ("description", "iconUrl", "name", "statusColor")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            # store undefined properties in additionalProperties
            if (!($AllProperties.Contains($name))) {
                $UpdatePriorityDetailsAdditionalProperties[$name] = $JsonParameters.PSobject.Properties[$name].value
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "iconUrl"))) { #optional property not found
            $IconUrl = $null
        } else {
            $IconUrl = $JsonParameters.PSobject.Properties["iconUrl"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "statusColor"))) { #optional property not found
            $StatusColor = $null
        } else {
            $StatusColor = $JsonParameters.PSobject.Properties["statusColor"].value
        }

        $PSO = [PSCustomObject]@{
            "description" = ${Description}
            "iconUrl" = ${IconUrl}
            "name" = ${Name}
            "statusColor" = ${StatusColor}
            "AdditionalProperties" = $UpdatePriorityDetailsAdditionalProperties
        }

        return $PSO
    }

}

