#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

A workflow scheme along with a list of projects that use it.

.PARAMETER ProjectIds
The list of projects that use the workflow scheme.
.PARAMETER WorkflowScheme
The workflow scheme.
.OUTPUTS

WorkflowSchemeAssociations<PSCustomObject>
#>

function Initialize-WorkflowSchemeAssociations {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${ProjectIds},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${WorkflowScheme}
    )

    Process {
        'Creating PSCustomObject: PSJira => WorkflowSchemeAssociations' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $ProjectIds) {
            throw "invalid value for 'ProjectIds', 'ProjectIds' cannot be null."
        }

        if ($null -eq $WorkflowScheme) {
            throw "invalid value for 'WorkflowScheme', 'WorkflowScheme' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "projectIds" = ${ProjectIds}
            "workflowScheme" = ${WorkflowScheme}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to WorkflowSchemeAssociations<PSCustomObject>

.DESCRIPTION

Convert from JSON to WorkflowSchemeAssociations<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

WorkflowSchemeAssociations<PSCustomObject>
#>
function ConvertFrom-JsonToWorkflowSchemeAssociations {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSJira => WorkflowSchemeAssociations' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in WorkflowSchemeAssociations
        $AllProperties = ("projectIds", "workflowScheme")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'projectIds' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "projectIds"))) {
            throw "Error! JSON cannot be serialized due to the required property 'projectIds' missing."
        } else {
            $ProjectIds = $JsonParameters.PSobject.Properties["projectIds"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "workflowScheme"))) {
            throw "Error! JSON cannot be serialized due to the required property 'workflowScheme' missing."
        } else {
            $WorkflowScheme = $JsonParameters.PSobject.Properties["workflowScheme"].value
        }

        $PSO = [PSCustomObject]@{
            "projectIds" = ${ProjectIds}
            "workflowScheme" = ${WorkflowScheme}
        }

        return $PSO
    }

}

