#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'AuditRecordsApi' {
    Context 'Get-AuditRecords' {
        It 'Test Get-AuditRecords' {
            #$TestResult = Get-AuditRecords -Offset "TEST_VALUE" -Limit "TEST_VALUE" -Filter "TEST_VALUE" -From "TEST_VALUE" -To "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
