#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'IssueRemoteLinksApi' {
    Context 'New-OrUpdateRemoteIssueLink' {
        It 'Test New-OrUpdateRemoteIssueLink' {
            #$TestResult = New-OrUpdateRemoteIssueLink -IssueIdOrKey "TEST_VALUE" -RemoteIssueLinkRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeleteRemoteIssueLinkByGlobalId' {
        It 'Test Invoke-DeleteRemoteIssueLinkByGlobalId' {
            #$TestResult = Invoke-DeleteRemoteIssueLinkByGlobalId -IssueIdOrKey "TEST_VALUE" -GlobalId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeleteRemoteIssueLinkById' {
        It 'Test Invoke-DeleteRemoteIssueLinkById' {
            #$TestResult = Invoke-DeleteRemoteIssueLinkById -IssueIdOrKey "TEST_VALUE" -LinkId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-RemoteIssueLinkById' {
        It 'Test Get-RemoteIssueLinkById' {
            #$TestResult = Get-RemoteIssueLinkById -IssueIdOrKey "TEST_VALUE" -LinkId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-RemoteIssueLinks' {
        It 'Test Get-RemoteIssueLinks' {
            #$TestResult = Get-RemoteIssueLinks -IssueIdOrKey "TEST_VALUE" -GlobalId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-RemoteIssueLink' {
        It 'Test Update-RemoteIssueLink' {
            #$TestResult = Update-RemoteIssueLink -IssueIdOrKey "TEST_VALUE" -LinkId "TEST_VALUE" -RemoteIssueLinkRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
