#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'IssueWatchersApi' {
    Context 'Add-Watcher' {
        It 'Test Add-Watcher' {
            #$TestResult = Add-Watcher -IssueIdOrKey "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-IsWatchingIssueBulk' {
        It 'Test Get-IsWatchingIssueBulk' {
            #$TestResult = Get-IsWatchingIssueBulk -IssueList "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-IssueWatchers' {
        It 'Test Get-IssueWatchers' {
            #$TestResult = Get-IssueWatchers -IssueIdOrKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Remove-Watcher' {
        It 'Test Remove-Watcher' {
            #$TestResult = Remove-Watcher -IssueIdOrKey "TEST_VALUE" -Username "TEST_VALUE" -AccountId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
