#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'PermissionSchemesApi' {
    Context 'New-PermissionGrant' {
        It 'Test New-PermissionGrant' {
            #$TestResult = New-PermissionGrant -SchemeId "TEST_VALUE" -PermissionGrant "TEST_VALUE" -Expand "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-PermissionScheme' {
        It 'Test New-PermissionScheme' {
            #$TestResult = New-PermissionScheme -PermissionScheme "TEST_VALUE" -Expand "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeletePermissionScheme' {
        It 'Test Invoke-DeletePermissionScheme' {
            #$TestResult = Invoke-DeletePermissionScheme -SchemeId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeletePermissionSchemeEntity' {
        It 'Test Invoke-DeletePermissionSchemeEntity' {
            #$TestResult = Invoke-DeletePermissionSchemeEntity -SchemeId "TEST_VALUE" -PermissionId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-AllPermissionSchemes' {
        It 'Test Get-AllPermissionSchemes' {
            #$TestResult = Get-AllPermissionSchemes -Expand "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-PermissionScheme' {
        It 'Test Get-PermissionScheme' {
            #$TestResult = Get-PermissionScheme -SchemeId "TEST_VALUE" -Expand "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-PermissionSchemeGrant' {
        It 'Test Get-PermissionSchemeGrant' {
            #$TestResult = Get-PermissionSchemeGrant -SchemeId "TEST_VALUE" -PermissionId "TEST_VALUE" -Expand "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-PermissionSchemeGrants' {
        It 'Test Get-PermissionSchemeGrants' {
            #$TestResult = Get-PermissionSchemeGrants -SchemeId "TEST_VALUE" -Expand "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-PermissionScheme' {
        It 'Test Update-PermissionScheme' {
            #$TestResult = Update-PermissionScheme -SchemeId "TEST_VALUE" -PermissionScheme "TEST_VALUE" -Expand "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
