#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'TimeTrackingApi' {
    Context 'Get-AvailableTimeTrackingImplementations' {
        It 'Test Get-AvailableTimeTrackingImplementations' {
            #$TestResult = Get-AvailableTimeTrackingImplementations
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SelectedTimeTrackingImplementation' {
        It 'Test Get-SelectedTimeTrackingImplementation' {
            #$TestResult = Get-SelectedTimeTrackingImplementation
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SharedTimeTrackingConfiguration' {
        It 'Test Get-SharedTimeTrackingConfiguration' {
            #$TestResult = Get-SharedTimeTrackingConfiguration
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Select-TimeTrackingImplementation' {
        It 'Test Select-TimeTrackingImplementation' {
            #$TestResult = Select-TimeTrackingImplementation -TimeTrackingProvider "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Set-SharedTimeTrackingConfiguration' {
        It 'Test Set-SharedTimeTrackingConfiguration' {
            #$TestResult = Set-SharedTimeTrackingConfiguration -TimeTrackingConfiguration "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
