#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'AnnouncementBannerConfigurationUpdate' {
    Context 'AnnouncementBannerConfigurationUpdate' {
        It 'Initialize-AnnouncementBannerConfigurationUpdate' {
            # a simple test to create an object
            #$NewObject = Initialize-AnnouncementBannerConfigurationUpdate -IsDismissible "TEST_VALUE" -IsEnabled "TEST_VALUE" -Message "TEST_VALUE" -Visibility "TEST_VALUE"
            #$NewObject | Should -BeOfType AnnouncementBannerConfigurationUpdate
            #$NewObject.property | Should -Be 0
        }
    }
}
