#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'CustomFieldContextDefaultValue' {
    Context 'CustomFieldContextDefaultValue' {
        It 'Initialize-CustomFieldContextDefaultValue' {
            # a simple test to create an object
            #$NewObject = Initialize-CustomFieldContextDefaultValue -CascadingOptionId "TEST_VALUE" -ContextId "TEST_VALUE" -OptionId "TEST_VALUE" -Type "TEST_VALUE" -OptionIds "TEST_VALUE" -AccountId "TEST_VALUE" -UserFilter "TEST_VALUE" -AccountIds "TEST_VALUE" -GroupId "TEST_VALUE" -GroupIds "TEST_VALUE" -Date "TEST_VALUE" -UseCurrent "TEST_VALUE" -DateTime "TEST_VALUE" -Url "TEST_VALUE" -ProjectId "TEST_VALUE" -Number "TEST_VALUE" -Labels "TEST_VALUE" -Text "TEST_VALUE" -VersionId "TEST_VALUE" -VersionOrder "TEST_VALUE" -VersionIds "TEST_VALUE" -Values "TEST_VALUE" -Object "TEST_VALUE"
            #$NewObject | Should -BeOfType CustomFieldContextDefaultValue
            #$NewObject.property | Should -Be 0
        }
    }
}
