#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'LinkIssueRequestJsonBean' {
    Context 'LinkIssueRequestJsonBean' {
        It 'Initialize-LinkIssueRequestJsonBean' {
            # a simple test to create an object
            #$NewObject = Initialize-LinkIssueRequestJsonBean -Comment "TEST_VALUE" -InwardIssue "TEST_VALUE" -OutwardIssue "TEST_VALUE" -Type "TEST_VALUE"
            #$NewObject | Should -BeOfType LinkIssueRequestJsonBean
            #$NewObject.property | Should -Be 0
        }
    }
}
