#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'OrderOfIssueTypes' {
    Context 'OrderOfIssueTypes' {
        It 'Initialize-OrderOfIssueTypes' {
            # a simple test to create an object
            #$NewObject = Initialize-OrderOfIssueTypes -After "TEST_VALUE" -IssueTypeIds "TEST_VALUE" -Position "TEST_VALUE"
            #$NewObject | Should -BeOfType OrderOfIssueTypes
            #$NewObject.property | Should -Be 0
        }
    }
}
