#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'PageOfCreateMetaIssueTypeWithField' {
    Context 'PageOfCreateMetaIssueTypeWithField' {
        It 'Initialize-PageOfCreateMetaIssueTypeWithField' {
            # a simple test to create an object
            #$NewObject = Initialize-PageOfCreateMetaIssueTypeWithField -Fields "TEST_VALUE" -MaxResults "TEST_VALUE" -Results "TEST_VALUE" -StartAt "TEST_VALUE" -Total "TEST_VALUE"
            #$NewObject | Should -BeOfType PageOfCreateMetaIssueTypeWithField
            #$NewObject.property | Should -Be 0
        }
    }
}
