#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ParsedJqlQuery' {
    Context 'ParsedJqlQuery' {
        It 'Initialize-ParsedJqlQuery' {
            # a simple test to create an object
            #$NewObject = Initialize-ParsedJqlQuery -Errors "TEST_VALUE" -Query "TEST_VALUE" -Structure "TEST_VALUE"
            #$NewObject | Should -BeOfType ParsedJqlQuery
            #$NewObject.property | Should -Be 0
        }
    }
}
