#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ProjectType' {
    Context 'ProjectType' {
        It 'Initialize-ProjectType' {
            # a simple test to create an object
            #$NewObject = Initialize-ProjectType -Color "TEST_VALUE" -DescriptionI18nKey "TEST_VALUE" -FormattedKey "TEST_VALUE" -Icon "TEST_VALUE" -Key "TEST_VALUE"
            #$NewObject | Should -BeOfType ProjectType
            #$NewObject.property | Should -Be 0
        }
    }
}
