#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'ServerInformation' {
    Context 'ServerInformation' {
        It 'Initialize-ServerInformation' {
            # a simple test to create an object
            #$NewObject = Initialize-ServerInformation -BaseUrl "TEST_VALUE" -BuildDate "TEST_VALUE" -BuildNumber "TEST_VALUE" -DeploymentType "TEST_VALUE" -DisplayUrl "TEST_VALUE" -DisplayUrlServicedeskHelpCenter "TEST_VALUE" -HealthChecks "TEST_VALUE" -ScmInfo "TEST_VALUE" -ServerTime "TEST_VALUE" -ServerTimeZone "TEST_VALUE" -ServerTitle "TEST_VALUE" -Version "TEST_VALUE" -VersionNumbers "TEST_VALUE"
            #$NewObject | Should -BeOfType ServerInformation
            #$NewObject.property | Should -Be 0
        }
    }
}
