#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'UiModificationDetails' {
    Context 'UiModificationDetails' {
        It 'Initialize-UiModificationDetails' {
            # a simple test to create an object
            #$NewObject = Initialize-UiModificationDetails -Contexts "TEST_VALUE" -VarData "TEST_VALUE" -Description "TEST_VALUE" -Id "TEST_VALUE" -Name "TEST_VALUE" -Self "TEST_VALUE"
            #$NewObject | Should -BeOfType UiModificationDetails
            #$NewObject.property | Should -Be 0
        }
    }
}
