#
# The Jira Cloud platform REST API
# Jira Cloud platform REST API documentation
# Version: 1001.0.0-SNAPSHOT-23ad6c5456aade2d59a4e9437ce49c945df2eb8f
# Contact: ecosystem@atlassian.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSJira' -name 'Visibility' {
    Context 'Visibility' {
        It 'Initialize-Visibility' {
            # a simple test to create an object
            #$NewObject = Initialize-Visibility -Identifier "TEST_VALUE" -Type "TEST_VALUE" -Value "TEST_VALUE"
            #$NewObject | Should -BeOfType Visibility
            #$NewObject.property | Should -Be 0
        }
    }
}
